// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWIudLcIoi8BpPZRITdyE-ojveKlWDdNM',
    appId: '1:957033456464:web:e4b09b27a1330381aec255',
    messagingSenderId: '957033456464',
    projectId: 'fir-app-658e1',
    authDomain: 'fir-app-658e1.firebaseapp.com',
    storageBucket: 'fir-app-658e1.firebasestorage.app',
    measurementId: 'G-N1PXM4BTQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD182qz6GNfgMeN-dOMwgrjkeJgeN27NQA',
    appId: '1:957033456464:android:adc5b9d71ddd8a5caec255',
    messagingSenderId: '957033456464',
    projectId: 'fir-app-658e1',
    storageBucket: 'fir-app-658e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCILInQnaM4eASBppcywT6ISHtOBjWluYU',
    appId: '1:957033456464:ios:68ad1a0dc0385d28aec255',
    messagingSenderId: '957033456464',
    projectId: 'fir-app-658e1',
    storageBucket: 'fir-app-658e1.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCILInQnaM4eASBppcywT6ISHtOBjWluYU',
    appId: '1:957033456464:ios:68ad1a0dc0385d28aec255',
    messagingSenderId: '957033456464',
    projectId: 'fir-app-658e1',
    storageBucket: 'fir-app-658e1.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWIudLcIoi8BpPZRITdyE-ojveKlWDdNM',
    appId: '1:957033456464:web:ed90773bfe04711daec255',
    messagingSenderId: '957033456464',
    projectId: 'fir-app-658e1',
    authDomain: 'fir-app-658e1.firebaseapp.com',
    storageBucket: 'fir-app-658e1.firebasestorage.app',
    measurementId: 'G-9W723YX1FC',
  );
}
