name: Flutter CI/CD

on:
  push:
    branches:
      - dev
      - test
      - release
      - main
  pull_request:
    branches:
      - dev
      - test
      - release
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'   # use your flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/release'
        run: flutter test

      - name: Run integration tests
        if: github.ref == 'refs/heads/test'
        run: flutter drive --target=test_driver/app.dart

      - name: Build web app
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'
        run: flutter build web

      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: your-project-id
