name: Test CI & Staging Deploy
on:
  pull_request:
    branches:
      - test

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Get dependencies
        run: flutter pub get

      - name: Run integration tests (placeholder)
        run: |
          echo "Run your integration tests here"
          # e.g. flutter drive or integration_test
          # If using firebase emulator, you would start it here.

      - name: Build web
        run: flutter build web

      - name: Deploy to Firebase (staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}"
          channelId: staging
          projectId: fir-app-658e1 
